Luna/turret
flamingchickens1540/bunnybots-delphi-2023 pull request #9
Opened 2023-12-09 03:30 UTC by gonzalezgonzalezl

I finished the Turret code! (at least for now)

2023-12-10 04:38 UTC, mimizh2418 requested changes
This code looks really good, you'll mostly just have to add a few motor configurations and add in the gear ratio conversions, along with a few minor stylistic things.

2023-12-10 04:38 UTC, mimizh2418 commented on src/main/java/org/team1540/bunnybotTank2023/Constants.java
> +        public static final int MOTOR_ID = 0; //TODO: FIGURE OUT CAN ID!!!!!
You can set the CAN ID to anything, as long as it doesn't conflict with any of the other motors. Make sure to check the other branches (`maddox/intake` and `alvin/shooter`) for CAN ID conflicts with anything in those branches as well.

2023-12-10 04:38 UTC, mimizh2418 commented on src/main/java/org/team1540/bunnybotTank2023/commands/turret/Turret.java
> +    }
Just a stylistic thing, you can name the input `TurretIO` as "`io`" too, and in the constructor just do `this.io = io` to avoid a naming conflict.

2023-12-10 04:38 UTC, mimizh2418 commented on src/main/java/org/team1540/bunnybotTank2023/Constants.java
> +        public static final double kD = 0.1;
aggressive kp hehehe (but really we'll tune them these are fine as placeholders)

2023-12-10 04:38 UTC, mimizh2418 commented on src/main/java/org/team1540/bunnybotTank2023/io/turret/TurretIOReal.java
> +    }
The rest of them have `@Override`, this should probably have it as well

2023-12-10 04:38 UTC, mimizh2418 commented on src/main/java/org/team1540/bunnybotTank2023/io/turret/TurretIO.java
> +        public double velocity = 0;
I would name these better, since something like "`currentPosition`" or "`velocity`" is ambiguous (do you mean the motor position/velocity, or the turret position/velocity? These are different because of the gearing between the motor and turret), so something specifying which part of the hardware each variable corresponds to would be clearer.

Also - it's good practice to include the units in your variable names, such as "`positionDegrees`" or "`velocityRPM`".

2023-12-10 04:38 UTC, mimizh2418 commented on src/main/java/org/team1540/bunnybotTank2023/io/turret/TurretIO.java
> +//TODO: GEAR RATIOS (Zach doesn't want to deal with them right now)
🙃

2023-12-10 04:38 UTC, mimizh2418 commented on src/main/java/org/team1540/bunnybotTank2023/io/turret/TurretIOReal.java
> +    final PositionVoltage positionVoltage = new PositionVoltage(0);
This should probably be private

2023-12-10 04:38 UTC, mimizh2418 commented on src/main/java/org/team1540/bunnybotTank2023/io/turret/TurretIOReal.java
> +        positionVoltage.Slot = 0;
You shouldn't need to specify the slot for the control request, as I believe it defaults to slot 0. If you want to explicitly declare the slot, I would probably do this in line with the field declaration (i.e. `PositionVoltage positionVoltage = new PositionVoltage(0).withSlot(0);`)

2023-12-10 04:38 UTC, mimizh2418 commented on src/main/java/org/team1540/bunnybotTank2023/io/turret/TurretIOReal.java
> +        motor.getConfigurator().apply(slot0Configs, 0.050);
In addition to configuring PID constants, you will also have to configure motor inversion, brake mode, and current limits here. The configuration can get pretty cluttered with so many parameters, so you might want to look into putting these configs into a separate file, such as in [Pesto's code](https://github.com/flamingchickens1540/pesto/blob/main/src/main/java/org/team1540/robot2023/CTREConfigs.java), or, more recently, in the [shooter code](https://github.com/flamingchickens1540/bunnybots-delphi-2023/blob/alvin/shooter/src/main/java/org/team1540/bunnybotTank2023/CTREConfigs.java)

2023-12-10 04:38 UTC, mimizh2418 commented on src/main/java/org/team1540/bunnybotTank2023/io/turret/TurretIOReal.java
You will have to add in the gear ratio calculations, but they should be relatively simple. There's already prewritten code to do the math for you (in the [`Conversions` class](https://github.com/flamingchickens1540/bunnybots-delphi-2023/blob/luna/turret/src/main/java/org/team1540/bunnybotTank2023/utils/Conversions.java)), so you just have to call `Conversions.motorRotsToRotation2d` to convert motor rotations to mechanism rotations, and `Conversions.Rotation2dToMotorRots` to convert mechanism rotations to motor rotations

2023-12-10 18:15 UTC, rutmanz commented on src/main/java/org/team1540/bunnybotTank2023/io/turret/TurretIO.java
> +//TODO: GEAR RATIOS (Zach doesn't want to deal with them right now)
🙄

2023-12-15 12:15 UTC, mimizh2418 approved these changes
LGTM

2023-12-15 12:15 UTC, merged